# Generated by Django 5.0.2 on 2024-03-01 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
